# Name
# Trigger
# Job
  # Steps

name: React CI

on: Push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm Install
      
      - name: Use Node.js
        uses: actions/setup-node@v4
      
      - name: Run Test
        run: npm run lint

        with:
          node-version: 18